### ISSUE TITLE
[8.1.1] Problems with the cron job

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/search_lucene#106]
Hi Guys,

I get this error while running the cron job:

PHP Fatal error:  Call to a member function isLocal() on a non-object in /var/www/owncloud/apps/search_lucene/db/statusmapper.php on line 173

Any ideas?

**Comment by karlitschek** [comment]
@butonic What do you think?

**Comment by pierrejochem** [comment]
It seems to be that this is no more needed :disappointed:
