### ISSUE TITLE
Enable fails with upgrade loop

### ISSUE THREAD

**Issue by joede** [owncloud/search_lucene#108]
I've upgraded my OC704 installation to 8.1.1 two week ago. After this upgrade, I've tried to enable Lucene Search. This fails. Directly after the activation, OC presents it's "start upgrade" page. This ends up with the following error message:

~~~~
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c3oc1.oc_queuedtasks' doesn't exist﻿
~~~~

The upgrade never leads to an login again. So I had to login with SSH and remove the app directory of `search_lucene`. 

In the G+ group of ownCloud I've read of an solution. The upgrade to the latest 81.3 should solve this problem. So I've upgraded my installation to 8.1.3 and tried Lucene Search again. With the same error message and the same loop!

I have verified this behaviour with my regular server (root server running Debian) and with my local server (Banana Pi with Debian). On both systems, I've installed ownCloud from the official tarball.

Note: since #90 is closed, I opened a new issue report!

**Comment by karlitschek** [comment]
@butonic can we fix this?

**Comment by VicDeo** [comment]
This is already fixed with https://github.com/owncloud/search_lucene/pull/102
What we need is to publish a fix

**Comment by joede** [comment]
@VicDeo hmm.... As far as I understand the conversation in #102, the problem should be solved. Or do you mean the app itself (lucene_search) must be published?

**Comment by RealRancor** [comment]
@joede Yes, a new release of search_lucene at the appstore is needed as the app is not shipped anymore in oC 8.1.

To get update notifications you can subscribe to the app page at https://apps.owncloud.com

**Comment by karlitschek** [comment]
@butonic Can you publish a new release? Thanks

**Comment by joede** [comment]
@RealRancor the `search_lucene` at the appstore still mentions OC8.1 as the intended release. What do you mean with *"the app is not shipped anymore in oC 8.1"*?
In my case, I never used it before 8.x. So If I enable it in an 8.1 installation, where is app install from? If `search_lucene` isn't compatible with OC8.1, this should be marked until the fix is available.

**Comment by RealRancor** [comment]
@joede Just download https://download.owncloud.org/community/owncloud-8.1.3.tar.bz2 where you can see which files are "shipped" within the core packages and are updated after each oC release. 

Everything else like calendar, contacts or search_lucene are pulled directly from apps.owncloud.com. And as the version there is not updated yet with the fix mentioned here you won't get an fix until some one is publishing a new version at the appstore.

> If search_lucene isn't compatible with OC8.1

search_lucene is compatible with oC 8.1.

**Comment by VicDeo** [comment]
v0.7.0. has been published at the app store meanwhile

**Comment by VicDeo** [comment]
@joede Please reopen if  package for 8.1 from https://apps.owncloud.com/content/show.php?content=168709 does  not fixes this issue.

**Comment by joede** [comment]
@VicDeo thanks a lot. I'l try it the next days.

**Comment by joede** [comment]
@VicDeo reinstallation now works as expected. Thanks again. I couldn't test the functionality after the installation (search copied word was not found). How long does is take until the index is build?
