### ISSUE TITLE
Correctly release 0.7.0 for 8.2

### ISSUE THREAD

**Issue by RealRancor** [owncloud/search_lucene#113]
Hi,

on a current oC 8.2.2 installation the search lucene app is showing up as version 0.6.0 within "not enabled", even if the search_lucene folder within the /apps folder doesn't exist.

It seems this is caused because 0.7.0 is only tagged for 8.1 at https://apps.owncloud.com/content/show.php?content=168709 and 0.6.0 is provided by the "All versions" download (which includes 8.2).

cc @VicDeo

**Comment by RealRancor** [comment]
It seems also the "All versions" download archive provides a wrong ocsid "166057" where "168709" should be correct. However this is already tracked at https://github.com/owncloud/search_lucene/issues/85

**Comment by RealRancor** [comment]
@PVince81 @LukasReschke Do you guys have any idea who we can pull in here to fix this mess? 

Probably not a good idea to provide such an outdated version to users, especially not for oC9 which might happen here as 0.6.0 don't has and max version.

**Comment by PVince81** [comment]
@butonic @karlitschek @LukasReschke  any idea?

**Comment by karlitschek** [comment]
@butonic what can we do here?

**Comment by RealRancor** [comment]
Ok, seems oC 8.2 and 9.0 won't get that old version 0.6.0 anymore:

https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=924&approved=all
https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=924&approved=all

so closing for now until a 8.2/9.0 compatible version is made available.
