### ISSUE TITLE
[7.0.1] open directory if search result is a directory

### ISSUE THREAD

**Issue by ferdiga** [owncloud/search_lucene#35]
Klicking on a search result which is a directory should open THIS directory not it's parent.

![image](https://cloud.githubusercontent.com/assets/6248560/3890184/48bd0dce-221b-11e4-8689-38fd58cfb432.png)

**Comment by VicDeo** [comment]
Not related to fulltext search. (And fixed in master)

**Comment by VicDeo** [comment]
Closed as a duplicate of https://github.com/owncloud/core/issues/11353
