### ISSUE TITLE
Files in sub-folders maching search results not clickable

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/search_lucene#56]
Original reported in https://github.com/owncloud/core/issues/13686 by @jnfrmarks 

### Steps to reproduce

1. Install owncloud
2. Upload an odt or pdf file that has owncloud in it
3. Create a subfolder
4. Upload a bunch of odt or pdf files that have owncloud in them
5. Search from the root for owncloud

### Expected behaviour

All files displayed in the search results to be clickable

### Actual behaviour

Only files found in the root are clickable

![p267](https://cloud.githubusercontent.com/assets/8480343/5906401/4b07c510-a565-11e4-804f-7f5d32a5e23c.PNG)

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by butonic** [comment]
closing, see https://github.com/owncloud/core/issues/13687#issuecomment-72069043
