### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

### ISSUE THREAD

**Issue by enoch85** [owncloud/search_lucene#60]
### Steps to reproduce

Don´t know.

### Expected behavior

No errors

### Actual behavior

Please see owncloud.log entries.

### oc_lucene_status table

```
SQL result

Host: localhost
Database: owncloud
Generation Time: Feb 12, 2015 at 11:16 PM
Generated by: phpMyAdmin 4.0.10deb1 / MySQL 5.5.41-0ubuntu0.14.04.1
SQL query: SELECT * FROM `oc_lucene_status` LIMIT 0, 30 ;
Rows: 30

fileid	status	
1		I
2		I
3		I 
12598	I
0		N
35		N
37		N
668		N
757		N
1358	N
8320	N
10274	N
10275	N
10288	N
10289	N
10290	N
10291	N
10292	N
10293	N
10294	N
10295	N
10296	N
10297	N
10298	N
10299	N
10300	N
10301	N
10302	N
10303	N
10304	N

```

### Server configuration

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
Update from 7.0.4

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1 and XP and Vista
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
Error	hook	error while running hook (OCA\Search_Lucene\Hooks\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params ["N"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'	2015-02-12T22:07:29+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params ["N"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'	2015-02-12T21:23:16+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params ["N"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'	2015-02-12T21:23:15+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params ["N"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'	2015-02-12T21:23:01+00:00
Error	hook	error while running hook (OCA\Search_Lucene\Hooks\Files::indexFile): An exception occurred while executing 'INSERT INTO `oc_lucene_status`(`status`) VALUES(?)' with params ["N"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'	2015-02-12T21:20:58+00:00
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

CC @butonic

**Comment by karlitschek** [comment]
@butonic Can you have a look?

**Comment by DeepDiver1975** [comment]
@butonic the reason with this error is that the function getOrCreateFromFileId() in
 https://github.com/owncloud/search_lucene/blob/master/db/statusmapper.php#L192 is not atomic.

Better user insertIfNotExist() on IDBConnection

**Comment by hupebln** [comment]
Are there any news related to that issue? I got the same issue and don't know how to fix that or if it has any impact to my ownCloud.

**Comment by dgerasimov** [comment]
Same problem here. I disabled search Lucene for now. Is there any other solution?

**Comment by butonic** [comment]
I'll have a look.

**Comment by dgerasimov** [comment]
OK, now I have this in log file - "app":"PHP","message":"Call to undefined method OC\\AppFramework\\Db\\Db::insertIfNotExist() at \/var\/www\/owncloud\/apps\/search_lucene\/db\/statusmapper.php#193","level":3.

**Comment by enoch85** [comment]
@dgerasimov Please open a new issue for that. Thanks.
