### ISSUE TITLE
Log flooded with "Error	search_lucene	Secured pdf file are currently not supported."

### ISSUE THREAD

**Issue by enoch85** [owncloud/search_lucene#61]
### Steps to reproduce

Don´t know.

### Expected behavior

Logged as debug maybe? Either way, I expect no errors when I'm not logging debug messages. 
CC @butonic 

### Actual behavior

```
Error	search_lucene	Secured pdf file are currently not supported. Trace:\n#0 /var/www/owncloud/apps/search_lucene/document/pdf.php(35): Smalot\PdfParser\Parser->parseContent('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n...') #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n...', false) #2 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n...') #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #4 /var/www/owncloud/apps/search_lucene/jobs/indexjob.php(41): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array) #5 /var/www/owncloud/lib/private/backgroundjob/job.php(36): OCA\Search_Lucene\Jobs\IndexJob->run(Array) #6 /var/www/owncloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #7 /var/www/owncloud/cron.php(125): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 {main}	2015-02-15T14:54:28+00:00
Error	search_lucene	Object list not found. Possible secured file. Trace:\n#0 /var/www/owncloud/apps/search_lucene/document/pdf.php(35): Smalot\PdfParser\Parser->parseContent('%PDF-1.4\r%\xE2\xE3\xCF\xD3\r...') #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.4\r%\xE2\xE3\xCF\xD3\r...', false) #2 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.4\r%\xE2\xE3\xCF\xD3\r...') #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #4 /var/www/owncloud/apps/search_lucene/jobs/indexjob.php(41): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array) #5 /var/www/owncloud/lib/private/backgroundjob/job.php(36): OCA\Search_Lucene\Jobs\IndexJob->run(Array) #6 /var/www/owncloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #7 /var/www/owncloud/cron.php(125): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 {main}	2015-02-15T14:54:22+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/apps/search_lucene/3rdparty/tecnick.com/tcpdf/tcpdf_parser.php#300	2015-02-15T14:54:22+00:00
Error	search_lucene	Missing catalog. Trace:\n#0 /var/www/owncloud/apps/search_lucene/3rdparty/smalot/pdfparser/src/Smalot/PdfParser/Document.php(250): Smalot\PdfParser\Document->getPages() #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(37): Smalot\PdfParser\Document->getText() #2 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.3\r1 0 ob...', false) #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.3\r1 0 ob...') #4 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #5 /var/www/owncloud/apps/search_lucene/jobs/indexjob.php(41): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array) #6 /var/www/owncloud/lib/private/backgroundjob/job.php(36): OCA\Search_Lucene\Jobs\IndexJob->run(Array) #7 /var/www/owncloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 /var/www/owncloud/cron.php(125): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #9 {main}	2015-02-15T14:54:20+00:00
Error	search_lucene	Missing catalog. Trace:\n#0 /var/www/owncloud/apps/search_lucene/3rdparty/smalot/pdfparser/src/Smalot/PdfParser/Document.php(250): Smalot\PdfParser\Document->getPages() #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(37): Smalot\PdfParser\Document->getText() #2 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.3\r1 0 ob...', false) #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.3\r1 0 ob...') #4 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #5 /var/www/owncloud/apps/search_lucene/jobs/indexjob.php(41): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array) #6 /var/www/owncloud/lib/private/backgroundjob/job.php(36): OCA\Search_Lucene\Jobs\IndexJob->run(Array) #7 /var/www/owncloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 /var/www/owncloud/cron.php(125): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #9 {main}	2015-02-15T14:54:05+00:00
Error	search_lucene	Secured pdf file are currently not supported. Trace:\n#0 /var/www/owncloud/apps/search_lucene/document/pdf.php(35): Smalot\PdfParser\Parser->parseContent('%PDF-1.6\r%\xE2\xE3\xCF\xD3\r...') #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.6\r%\xE2\xE3\xCF\xD3\r...', false) #2 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.6\r%\xE2\xE3\xCF\xD3\r...') #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #4 /var/www/owncloud/apps/search_lucene/jobs/indexjob.php(41): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array) #5 /var/www/owncloud/lib/private/backgroundjob/job.php(36): OCA\Search_Lucene\Jobs\IndexJob->run(Array) #6 /var/www/owncloud/lib/private/backgroundjob/queuedjob.php(27): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #7 /var/www/owncloud/cron.php(125): OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)) #8 {main}	2015-02-15T14:53:55+00:00
Error	PHP	Array to string conversion at /var/www/owncloud/apps/search_lucene/3rdparty/zendframework/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php#341
```

### Server configuration

Ubuntu Server 12.04

**Database:**
Server version: 5.5.41-0ubuntu0.12.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
5, 6, 7.

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
As mentioned above
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by karlitschek** [comment]
@butonic can you have a look please?

**Comment by butonic** [comment]
Agreed, should be debug level log.

**Comment by Killer1337** [comment]
I am getting these too. What's behind it?

**Comment by karlitschek** [comment]
@butonic Can you help to fix that?

**Comment by MorrisJobke** [comment]
Will be fixed with 8.0.2

**Comment by bennidi** [comment]
It seems I am still seeing this error in 8.0.2 (stable) running on Ubuntu 14.04 with PHP 5.5.9-1ubuntu4.7php.

Log excerpt (Error Search Lucene):
```Object list not found. Possible secured file. Trace:\n#0 /var/www/owncloud/apps/search_lucene/document/pdf.php(35): Smalot\PdfParser\Parser->parseContent('%PDF-1.5?%?????...') #1 /var/www/owncloud/apps/search_lucene/document/pdf.php(69): OCA\Search_Lucene\Document\Pdf->__construct('%PDF-1.5?%?????...', false) #2 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(207): OCA\Search_Lucene\Document\Pdf::loadPdf('%PDF-1.5?%?????...') #3 /var/www/owncloud/apps/search_lucene/lucene/indexer.php(132): OCA\Search_Lucene\Lucene\Indexer->indexFile(Object(OC\Files\Node\File), false) #4 /var/www/owncloud/apps/search_lucene/controller/apicontroller.php(68): OCA\Search_Lucene\Lucene\Indexer->indexFiles(Array, Object(OC_EventSource)) #5 [internal function]: OCA\Search_Lucene\Controller\ApiController->index(NULL) #6 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array) #7 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Search_Lucene\Controller\ApiController), 'index') #8 /var/www/owncloud/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Search_Lucene\Controller\ApiController), 'index') #9 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('ApiController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #10 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array) #11 /var/www/owncloud/lib/private/route/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array) #12 /var/www/owncloud/lib/base.php(767): OC\Route\Router->match('/apps/search_lu...') #13 /var/www/owncloud/index.php(36): OC::handleRequest() #14 {main} ```

**Comment by enoch85** [comment]
@MorrisJobke Any comment on @bennidis post?

**Comment by sedrubal** [comment]
can confirm that it is not fixed in `8.0.2`. After catching any exception a new one will be thrown and there is a `TODO` comment ;)

**Comment by enoch85** [comment]
@sedrubal Thanks for the confirmation.

**Comment by VicDeo** [comment]
@sedrubal 8.x doesn't ship Search Lucene anymore and the app is not updated with OC update.
Please try with recent stable8 branch https://github.com/owncloud/search_lucene/archive/stable8.zip

**Comment by sedrubal** [comment]
I have the latest version of `search_lucene` on branch `stable8` installed. I also detected that the search does not work at all since upgrading to `oc8`

**Comment by VicDeo** [comment]
@sedrubal can you show me where the new exception is thrown?
As I see it is handled here 
https://github.com/owncloud/search_lucene/blob/stable8/lucene/indexer.php#L149

**Comment by sedrubal** [comment]
ah I'm sorry, I have the same file as it  is in the git and I can't find the error anymore. So it semms to be fixed...
