### ISSUE TITLE
Re-Index

### ISSUE THREAD

**Issue by witchi** [owncloud/search_lucene#71]
How I can manually re-index all files of a user?

**Comment by butonic** [comment]
Currently there is no UI for that. You have to DELETE the fileids belonging to a user from the status table.
If you only have a user ID you can check the full text indexing status of the users root storage by executing
```SQL
SELECT ls.fileid, ls.status, fc.path
FROM oc_lucene_status ls
    JOIN oc_filecache fc ON fc.fileid=ls.fileid
    JOIN oc_storages s ON fc.storage=s.numeric_id
WHERE s.id='home::<yourusername>';
```

After deleting these ids from the status table lucene will reindex on the next cron run. On mysql you need a temp table hack or you will encounter `ERROR 1093 (HY000): You can't specify target table 'oc_lucene_status' for update in FROM clause`:
```SQL
DELETE FROM oc_lucene_status
WHERE fileid in (
    SELECT id FROM (
        SELECT ls.fileid id
        FROM oc_lucene_status ls
            JOIN oc_filecache fc ON fc.fileid=ls.fileid
            JOIN oc_storages s ON fc.storage=s.numeric_id
        WHERE s.id='home::<yourusername>'
    ) mysqlhack
);
```

**Comment by witchi** [comment]
Thank you, it works!
