### ISSUE TITLE
Error PHP Call to undefined method OC\AppFramework\Db\Db::insertIfNotExist()

### ISSUE THREAD

**Issue by dgerasimov** [owncloud/search_lucene#74]
### Steps to reproduce
1. After implemeting this solution https://github.com/owncloud/search_lucene/pull/73

### Expected behaviour

No errors

### Actual behaviour

Please see owncloud.log posted bellow

### Server configuration
**Operating system**:

Debian GNU/Linux 7.6 (wheezy)

**Web server:**
nginx/1.2.1

**Database:**
Server version: 5.5.40-0+wheezy1 (Debian)

**PHP version:**
PHP 5.4.36-0+deb7u1 (cli)

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.0.2 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated from 7.0.4

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Iceweasel 36.0.1
**Operating system:**
Debian 8 (testing)

#### ownCloud log (data/owncloud.log)
Error PHP Call to undefined method OC\AppFramework\Db\Db::insertIfNotExist() at /var/www/owncloud/apps/search_lucene/db/statusmapper.php#193
Error PHP Call to undefined method OC\AppFramework\Db\Db::insertIfNotExist() at /var/www/owncloud/apps/search_lucene/db/statusmapper.php#193

**Comment by karlitschek** [comment]
@butonic any idea?

**Comment by VicDeo** [comment]
@dgerasimov because #60 is for master.
`OC\AppFramework\Db\Db::insertIfNotExist` function exists in master
 https://github.com/owncloud/core/blob/master/lib/private/appframework/db/db.php#L136 
and is not implemented for stable8  https://github.com/owncloud/core/blob/stable8/lib/private/appframework/db/db.php

**Comment by DeepDiver1975** [comment]
invalid configuration -> close

**Comment by VicDeo** [comment]
@dgerasimov for ownCloud 8 please use https://github.com/owncloud/search_lucene/pull/79
