### ISSUE TITLE
[oc 8.0.2] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1

### ISSUE THREAD

**Issue by ma-ver-ick** [owncloud/search_lucene#75]
Hello!

The owncloud log is flooded with the following messages:

```
error while running hook (OCA\Search_Lucene\Hooks::indexFile): An exception occurred while executing 'INSERT INTO `oc_jobs`(`class`, `argument`, `last_run`) VALUES(?, ?, 0)' with params ["OC\\BackgroundJob\\Legacy\\QueuedJob", "{\"app\":\"search_lucene\",\"klass\":\"OCA\\\\Search_Lucene\\\\Hooks\",\"method\":\"doIndexFile\",\"parameters\":\"{\\\"[... I snipped that, because it's private :) ...]\\\",\\\"user\\\":\\\"msei\\\"}\"}"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'argument' at row 1
```

What to do? Is it allowed (as a workaround) to enlarge the column? I'm using MySQL

**Comment by DeepDiver1975** [comment]
@ma-ver-ick what versions are you using?

**Comment by ma-ver-ick** [comment]
Owncloud 8.0.2 and search_lucene 0.6.0.

**Comment by VicDeo** [comment]
hm argument length is 256 for 8.x
https://github.com/owncloud/core/blob/stable8/db_structure.xml#L982
and 4000 for master
https://github.com/owncloud/core/blob/master/db_structure.xml#L899

**Comment by VicDeo** [comment]
@ma-ver-ick I guess you are upgraded from OC7. How long ago it happened?

**Comment by ma-ver-ick** [comment]
Not long ago, I rechecked and search_lucene hasn't been upgraded :( I upgraded now but I can't confirm that the database column has been upgraded, as I did that manually before.
The oc upgrade from 7 to 8 is AWFUL. 

So I can upgrade it to 4000 manually and everything should be ok? Still lucene should rethink that argument, there are still path's that could be longer than 4000 (but more unlikely as with 256).

Thanks for taking time to help me!

**Comment by VicDeo** [comment]
@ma-ver-ick method `doIndexFile` and was removed here https://github.com/owncloud/search_lucene/commit/ae8f726754b6630f27e09df382d9aa2a027d0593#diff-01a8cbfd57776618e73594448f061365

I guess you  need to update the app  from the current stable8 branch https://github.com/owncloud/search_lucene/archive/stable8.zip

@DeepDiver1975 this seems to be fixed for OC8

**Comment by VicDeo** [comment]
Stable7 still affected (argument is too small to have a long path inside):
https://github.com/owncloud/search_lucene/blob/stable7/lib/hooks.php#L58
https://github.com/owncloud/core/blob/stable7/db_structure.xml#L978

**Comment by DeepDiver1975** [comment]
please upgrade - thx
