### ISSUE TITLE
Log polluted - Error while running background job: Path exists, but it's not a directory

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/search_lucene#81]
No need to log this - simple ignore

````
{"reqId":"8RZIxXunfGXAMkGqWHHX","remoteAddr":"::1","app":"no app in context","message":"Error while running background job: Path exists, but it's not a directory","level":3,"time":"2015-04-14T08:11:35+00:00","method":"GET","url":"\/oc\/core\/cron.php"}

**Comment by VicDeo** [comment]
@DeepDiver1975 this message  is produced by ZendSearch exception. Any chance to have a full stacktrace?

**Comment by VicDeo** [comment]
@DeepDiver1975 please disregard a previous comment. I have one.

**Comment by VicDeo** [comment]
@DeepDiver1975 the storage is wrapped with encryption wrapper even when the Encryption app is disabled. It overrides getLocalFile implementation. 
![storage](https://cloud.githubusercontent.com/assets/991300/7147941/6d70afb0-e307-11e4-9c9d-9ca458793e6e.png)

**Comment by VicDeo** [comment]
@DeepDiver1975 ok, fix is pushed. Just for the note: overriding `getLocalFile` as above makes nearly impossible to get an absolute path from `OC\Files\Node\File` object instance and might affect many other apps.
