### ISSUE TITLE
Can't open search result

### ISSUE THREAD

**Issue by scream88** [owncloud/search_lucene#88]
Steps to reproduce:
Search in OwnCloud fulltext search in users root folder for a string in a document.
A few pdf-documents are displayed. Click on one of them to open them.

Expected behaviour:
Possibility 1: Open the pdf-preview to show the selected file.
Possibility 2: Jump in folder location and scroll to the right file & mark them.

Actual behaviour:
Only jump in the file-location folder. No autoscroll or file mark. I've search the file in this folder again manually.

Server Host info:
Ubuntu-Server 14.04.2 LTS Trusty Tahr - Release amd64
Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
OwnCloud 8.0.3 stable

**Comment by DeepDiver1975** [comment]
@VicDeo can you please have a look? THX

**Comment by scream88** [comment]
Update: Add Pictures.
Picture 1:
Searching for a string in a Document and select File "image.58.pdf"
![owncloud_search_issue_1](https://cloud.githubusercontent.com/assets/12324196/7811637/4b63d3a0-03ac-11e5-9edd-edcfd22cee8a.JPG)

Picture 2:
It jumps to the folder "pdf / 2013" but don't show the file "image.58.pdf" and also not open it. Im on top of the folder and have to scroll down to the right file I've selected in step 1.
![owncloud_search_issue_2](https://cloud.githubusercontent.com/assets/12324196/7811638/4b99b47a-03ac-11e5-922e-f7f24831b2f4.JPG)

**Comment by scream88** [comment]
Same issue with OwnCloud 8.1 and seach_lucene 0.6.0. Bugfix please.

**Comment by scream88** [comment]
@VicDeo Can you have a look at this open bug?

**Comment by scream88** [comment]
Thank you verry much. Works perfect!
