### ISSUE TITLE
oc_queuedtasks doesn't exist but is accessed

### ISSUE THREAD

**Issue by Aikhjarto** [owncloud/search_lucene#90]
I just upgraded from 8.0.5 to 8.1 and wanted to enable search_lucene again. However, the upgrade of serach_lucene tries to access oc_queuedtasks which is deprecated according to https://doc.owncloud.com/server/8.0/ownCloudServerAdminManual.pdf and not existing on my system any more.

```
Updating <search_lucene> ...
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_queuedtasks` WHERE `app`=?' with params ["search_lucene"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_queuedtasks' doesn't exist
Update failed
Maintenance mode is kept active
```

IMHO the upgrade shouldn't stop if a deprecated table is not existing.

**Comment by karlitschek** [comment]
@butonic Can you have a look please?

**Comment by DeepDiver1975** [comment]
access during upgrade - https://github.com/owncloud/search_lucene/blob/master/appinfo/update.php#L16

**Comment by alexplusde** [comment]
As I had the same problem and didn't find any solution for this problem, I will document my "solution":
I commented out #16 and #17, ran the upgrade and set the config.php maintanance value back to false. This worked for me.

Please don't forget to provide information that will help non-developers (like me) to solve their problems.

**Comment by kas70** [comment]
i got the same error when upgrading stable to 8.1.3.
@alexplusde can you tell me which lines i have to comment out?
