### ISSUE TITLE
ODT documents badly indexed (and proposed fix)

### ISSUE THREAD

**Issue by fifh** [owncloud/search_lucene#97]
### Steps to reproduce
1. create a new odt document "test.odt" with this content : <BR>
new<BR>
libreoffice<BR>
document
2. wait for indexing (or run cron.php) and then search "libreoffice"

### Expected behaviour
OC (actually the "search lucene" app) should find the test.odt document

### Actual behaviour
OC doesn't find it
Actually the last word of each line (except the last line) and the first word of each line (except the first line) are not well indexed

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache 2.4.6
**Database:**
MySQL 5.5
**PHP version:**
5.4
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
search lucene 0.6.0
documents 0.10.1
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Firefox
**Operating system:**
Linux, Windows 8

### Proposed fix

There is a bug when reading the document content in document/odt.php.
The paragraphs are concatenated without any character to separate them.
So in my example if you search "newlibreofficedocument" you will find the test.odt document.
In document/odt.php, lines 77 and 80, we just need to add a space as a argument in the "implode" function : 
$this->addField(Field::UnStored('body', implode('', $documentParagraphs), 'UTF-8'));
become
$this->addField(Field::UnStored('body', implode(' ', $documentParagraphs), 'UTF-8'));

I tested it and it works.

**Comment by DeepDiver1975** [comment]
Thanks a lot for the fix! Please submit a pull request - THX

**Comment by DeepDiver1975** [comment]
@butonic @VicDeo FYI

**Comment by fifh** [comment]
Ok, here is the pull request : https://github.com/owncloud/search_lucene/pull/98
