### ISSUE TITLE
installation on owncloud 8.1 from integrated appstore failes

### ISSUE THREAD

**Issue by michag86** [owncloud/search_lucene#99]
Installation of search_lucene failes on owncloud 8.1 from integrated appstore.
directory name in package is wrong
Actual name: search_lucene-8.1.1
Expected name: search_lucene

**Comment by DeepDiver1975** [comment]
@VicDeo can you please upload the correct archive?

**Comment by VicDeo** [comment]
@michag86  @DeepDiver1975 Done.
Published as https://github.com/owncloud/search_lucene/releases/download/8.1.1/search_lucene.zip

**Comment by michag86** [comment]
Works! Thank you!
